Server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=api/auth/**
        - id: user-service
          uri: lb://user-service
          filters:
            - name: JWTAuthenticationFilterFactory
          predicates:
            - Path=api/user/**
            - Path=api/friends/**
    kubernetes:
      discovery:
        enabled: true
