Server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=api/auth/**
        - id: user-service
          uri: lb://user-service
          filters:
            - TokenRelay=Authorization
            - name: JwtAuthenticationFilter
          predicates:
            - Path=api/user/**
            - Path=api/friends/**
    kubernetes:
      discovery:
        enabled: true