server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.messenger.api_gateway: DEBUG
spring:
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  main:
    web-application-type: reactive
  autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/login,/api/auth/register,/api/auth/verify

        - id: auth-service
          uri: http://auth-service:8081
          filters:
            - name: AuthenticationFilter
          predicates:
            - Path=/api/auth/logout

        - id: user-service
          uri: http://user-service:8082
          filters:
            - name: AuthenticationFilter
          predicates:
            - Path=/api/user/**
            - Path=/api/friends/**


    kubernetes:
      discovery:
        enabled: true

