server:
  port: 8080  # ????, ?? ??????? ????? ???????? API Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service1  # ?????????? ????????????? ????????
          uri: http://localhost:8081  # ????? ???????????? service1
          predicates:
            - Path=/service1/**  # ????????????? ?? ???? /service1/**

        - id: service2  # ?????????? ????????????? ????????
          uri: http://localhost:8082  # ????? ???????????? service2
          predicates:
            - Path=/service2/**  # ????????????? ?? ???? /service2/**