create table private_chat
(
    id          int primary key generated by default as identity,
    sender_id int not null ,
    receiver_id int not null ,
    created_at  timestamp default now()
);
create table private_chat_messages
(
    id              int primary key generated by default as identity,
    private_chat_id int references private_chat (id) on delete cascade,
    sender_id       int not null ,
    receiver_id    int not null ,
    sent_at         timestamp default now(),
    status          varchar,
    message         text
);
create table private_chat_files
(
    id              int primary key generated by default as identity,
    private_chat_id int references private_chat (id) on delete cascade,
    sender_id       int not null ,
    receiver_id    int not null ,
    sent_at         timestamp default now(),
    file_name       varchar,
    file_path varchar,
    type            varchar(10),
    size int
);