server:
  port: 8082
spring:
  application:
      name: user-service
  cloud:
      kubernetes:
        discovery:
          enabled: true
  # DB
  datasource:
    url: ${DB_USER_URL}
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate: TRACE

  docker:
    compose:
      enabled: false

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region:
    static: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET}

services:
  presence:
    url: ${PRESENCE_SERVICE_URL}