create table group_chat
(
    id          int primary key generated by default as identity,
    name        varchar(60) not null,
    description varchar,
    created_at  timestamp default now(),
    avatar varchar
);
create table group_chat_messages
(
    id            int primary key generated by default as identity,
    group_chat_id int references group_chat (id) on delete cascade,
    sender_id     int not null,
    sent_at       timestamp default now(),
    status          varchar,
    message       text
);
create table group_chat_files
(
    id            int primary key generated by default as identity,
    group_chat_id int references group_chat (id) on delete cascade,
    sender_id     int not null,
    sent_at       timestamp default now(),
    file_name     varchar,
    file_path varchar,
    type          varchar(10),
    size int
);
create table group_chat_members
(
    id            int primary key generated by default as identity,
    group_chat_id int references group_chat (id) on delete cascade,
    member_id     int not null,
    role          varchar(10) not null,
    applied_at timestamp default now()
);