CREATE USER ${DB_USER_USERNAME} WITH PASSWORD ${DB_USER_PASSWORD};
CREATE DATABASE ${DB_USER_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${DB_USER_NAME} TO ${DB_USER_USERNAME};
ALTER USER postgres WITH PASSWORD ${POSTGRES_ADMIN_PASSWORD};
create table user_profile
(
    id           int primary key generated by default as identity,
    username     varchar(60) unique not null,
    password     varchar(64)        not null,
    nickname     varchar(60) unique not null,
    status       varchar            not null, --
    phone_number varchar(10) unique not null,
    email        varchar(50) unique not null,
    avatar   varchar,
    created_at   timestamp          default now()
);
create table friend_list
(
    id        int primary key generated by default as identity,
    user_id   int references user_profile (id) on delete cascade,
    friend_id int references user_profile (id) on delete cascade,
    added_at  timestamp not null default now()
);