server:
  port: 8083

api:
  gateway:
    url: ${GATEWAY_URL}

spring:

  application:
    name: chat-service

  cloud:
    kubernetes:
      discovery:
        enabled: true

  data:
    redis:
      host: redis
      port: 6379
      database: 1

  datasource:
    url: ${DB_CHATS_URL}
    username: ${DB_CHATS_USERNAME}
    password: ${DB_CHATS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate: TRACE

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region:
    static: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET}